### ISSUE TITLE
count(): int leads to errors in icingaweb2 VSphereDB & Director

### ISSUE THREAD

**Issue by jprusch** [Icinga/icinga-php-library#12]
I'm not a programmer but:

VERSION:
0.8.1+4+gb5c5a8b

`
    public function count(): int
    {
        return count($this->content);
    }
`

leads to:

Fatal error
: Declaration of Icinga\Module\Director\Dashboard\Dashboard::count() must be compatible with ipl\Html\HtmlDocument::count(): int in
/usr/share/icingaweb2/modules/director/library/Director/Dashboard/Dashboard.php
on line 152

and also

Fatal error
: Declaration of Icinga\Module\Director\Dashboard\Dashboard::count() must be compatible with ipl\Html\HtmlDocument::count(): int in
/usr/share/icingaweb2/modules/director/library/Director/Dashboard/Dashboard.php
on line
152

Not sure, if this should be fixed here or in the modules....

**Comment by jprusch** [comment]
This seems already fixed in ipl-html, but not in this bundle.

**Comment by nilmerg** [comment]
Snapshots were updated recently, should be fixed there.
