### ISSUE TITLE
installing IPL 0.9.0 renders icingaweb2 useless (text only)

### ISSUE THREAD

**Issue by stultitiophobia** [Icinga/icinga-php-library#13]
when using INSTALL_VERSION="v0.8.1" icingaweb2 looks great with graphics and all (how it should)

<img width="186" alt="image" src="https://user-images.githubusercontent.com/809290/173936689-fccad9ef-a171-4205-a1f6-cf44dc4fcd53.png">

when using INSTALL_VERSION="v0.9.0"iicngaweb2 lost all graphics and is text only

<img width="351" alt="image" src="https://user-images.githubusercontent.com/809290/173936354-0dde1d40-1cb9-4b6f-92b6-2e521311837f.png">

my system should be up to date ...
<img width="524" alt="image" src="https://user-images.githubusercontent.com/809290/173937683-76f8ca6c-0baa-40d6-9350-1ab9cd44be1e.png">

does anyone have some idea on hoot "unbreak" this - installing the 0.8.1 renders cube and graphite in the latest versions useless...

**Comment by lippserd** [comment]
Hi,

Can you please visit the Icinga Web 2 URL css/icinga.css which should yield an error and share the output?

All the best,
Eric

**Comment by stultitiophobia** [comment]
Hi, Eric !
This is with 0.9.0

Operation on an invalid type
#0 /usr/share/icingaweb2/library/vendor/lessphp/lib/Less/Tree/Expression.php(51): Less_Tree_Operation->compile()
#1 /usr/share/icingaweb2/library/vendor/lessphp/lib/Less/Tree/Call.php(44): Less_Tree_Expression->compile()
#2 /usr/share/icingaweb2/library/vendor/lessphp/lib/Less/Tree/Expression.php(51): Less_Tree_Call->compile()
#3 /usr/share/icingaweb2/library/vendor/lessphp/lib/Less/Tree/Value.php(26): Less_Tree_Expression->compile()
#4 /usr/share/icingaweb2/library/vendor/lessphp/lib/Less/Tree/Rule.php(73): Less_Tree_Value->compile()
#5 /usr/share/icingaweb2/library/vendor/lessphp/lib/Less/Tree/Ruleset.php(91): Less_Tree_Rule->compile()
#6 /usr/share/icingaweb2/library/vendor/lessphp/lib/Less/Tree/Ruleset.php(91): Less_Tree_Ruleset->compile()
#7 /usr/share/icingaweb2/library/vendor/lessphp/lib/Less/Parser.php(185): Less_Tree_Ruleset->compile()
#8 /usr/share/icingaweb2/library/vendor/lessphp/lessc.inc.php(130): Less_Parser->getCss()
#9 /usr/share/php/Icinga/Web/LessCompiler.php(230): lessc->compile()
#10 /usr/share/php/Icinga/Web/StyleSheet.php(218): Icinga\Web\LessCompiler->render()
#11 /usr/share/php/Icinga/Web/StyleSheet.php(258): Icinga\Web\StyleSheet->render()
#12 /usr/share/php/Icinga/Application/webrouter.php(60): Icinga\Web\StyleSheet::send()
#13 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#14 {main}


.. 07143em;
     vertical-align: 0.05357em; }
   
   .fa-lg {
     font-size: 1.25em;
     line-height: 0.05em;
     vertical-align: -0.075em; }
   
   .fa-xl {
     font-size: 1.5em;
     line-height: 0.04167em;
     vertical-align: -0.125em; }
   
   .fa-2xl {
     font-size: 2em;
     line-height: 0.03125em;
     vertical-align: -0.1875em; }
   
   .fa-fw {
     text-align: center;
     width: 1.25em; }
   
   .fa-ul {
     list-style-type: none;
     margin-left: var(--fa-li-margin, 2.5em);
     padding-left: 0; }
     .fa-ul > li {
       position: relative; }
   
   .fa-li {
!!   left: calc(var(--fa-li-width, 2em) * -1);
     position: absolute;
     text-align: center;
     width: var(--fa-li-width, 2em);
     line-height: inherit; }
   
   .fa-border {
     border-color: var(--fa-border-color, #eee);
     border-radius: var(--fa-border-radius, 0.1em);
     border-style: var(--fa-border-style, solid);
     border-width: var(--fa-border-width, 0.08em);
     padding: var(--fa-border-padding, 0.2em 0.25em 0.15em); }
   
   .fa-pull-left {
     float: left;
     margin-right: var(--fa-pull-margin, 0.3em); }
   
   .fa-pull-
..

**Comment by stultitiophobia** [comment]
no error with 0.8.1 but lots of content ;-)

**Comment by lippserd** [comment]
Seems like the font awesome upgrade breaks our CSS parser. I’ll have a look at this asap. You could try to decrease the font awesome version to 5 in the composer.json file and run composer install.

**Comment by lippserd** [comment]
I missed one important thing: You need Icinga Web 2.10.2!

**Comment by stultitiophobia** [comment]
Ah, I see.
So I'll have to wait until the Ubuntu repository für icingaweb2 is updated, i think ?

But wait - is .2 even released ?

**Comment by fireba11** [comment]
ah. please note things like "requires icinga web 2.10.2" in the release notes ;-)
FYI: for my centos8 stream latest is 2.9.5

**Comment by herman-the-worm** [comment]
@fireba11 for centos8 stream latest (2.9.5) IPL for 0.8.1 worked just fine

Thanks

**Comment by nilmerg** [comment]
Updated the release notes.

Hint: If you're installing icingaweb2 by package, install icinga-php-library this way as well. Then things don't break this easily.

**Comment by fireba11** [comment]
@nilmerg i'm not aware of any repo for centos8 stream that contains a ipl package i could use.
@herman-the-worm i know, was just too fast in updating :-)

**Comment by herman-the-worm** [comment]
@fireba11 any issues with building icinga dashboard with "bundle"?

**Comment by kosli** [comment]
@fireba11 
same issues happened to me today with the Debian (bullseye) packages. icinga-php-library is now on version 0.9.0-1-bullseye, whereas there is no icingaweb 2.10.2 debian package available yet :-( 
downgrading the debian package to 0.8.0 resolves the issue, but still not good practice to not have a "require" for that icingaweb version in the icinga-php-library package :-(

**Comment by maggu** [comment]
Yep. Me too on CentOS 7. Got  icinga-php-library upgraded to 0.9.0, but no 2.10.2 package yet.

**Comment by kochd** [comment]
Updating on 
https://packages.icinga.com/debian/dists/icinga-bullseye/ 
breaks icingaweb2 because 
icingaweb2 is 2.10.1
icinga-php-library is 0.9.0

If you are affected:
Downgrade to 0.8.0
`apt install icinga-php-library=0.8.0-1.bullseye`
