### ISSUE TITLE
Icingaweb2 error  Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 7.2.0". You are running 7.1.30

### ISSUE THREAD

**Issue by zerocarbthirty** [Icinga/icinga-php-library#14]
Hello,

I am getting an error trying to use icingaweb2 after upgrading. It appears that this package (icinga-php-library) thinks that php 7.1 is installed on this host but it is actually running php 7.2.43 in both apache and in the CLI.

The actual error is Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 7.2.0". You are running 7.1.30. in /usr/share/icinga-php/ipl/vendor/composer/platform_check.php on line 24

The library came from here: 

Name        : icinga-php-library
Arch        : noarch
Version     : 0.9.1
Release     : 1.el7.icinga
Size        : 6.7 M
Repo        : installed
From repo   : icinga-stable-release

Can you tell me how this is being checked?

**Comment by nilmerg** [comment]
Hi,

please take a look [here](https://community.icinga.com/t/icingaweb2-seeing-wrong-php-version/10199). Such questions are best to be asked in the forums :)
