### ISSUE TITLE
Awesome Font Files returns an 404

### ISSUE THREAD

**Issue by neubi4** [Icinga/icinga-php-library#17]
Hi,

we are using Icingaweb2 v2.11.2 with ipl v0.10.0.

The webinterface tries to load the Awesome Font Files via this URL `lib/icinga/icinga-php-library/font/awesome/fa-solid-900.woff2`, but we get back an 404 HTTP Error Code.

Since the 404 Page is empty, i believe that the php code throws this error. The Font files are in the corrent path:
```
root@master-0:/usr/share/icingaweb2# ls -la /usr/share/icinga-php/ipl/asset/static/font/awesome/
total 952
drwxr-xr-x 2 root root   4096 Nov  1 16:58 .
drwxr-xr-x 3 root root   4096 Nov  1 16:58 ..
-rw-r--r-- 1 root root 186112 Nov  1 16:58 fa-brands-400.ttf
-rw-r--r-- 1 root root 107460 Nov  1 16:58 fa-brands-400.woff2
-rw-r--r-- 1 root root  62048 Nov  1 16:58 fa-regular-400.ttf
-rw-r--r-- 1 root root  25084 Nov  1 16:58 fa-regular-400.woff2
-rw-r--r-- 1 root root 397728 Nov  1 16:58 fa-solid-900.ttf
-rw-r--r-- 1 root root 150468 Nov  1 16:58 fa-solid-900.woff2
-rw-r--r-- 1 root root  10136 Nov  1 16:58 fa-v4compatibility.ttf
-rw-r--r-- 1 root root   4584 Nov  1 16:58 fa-v4compatibility.woff2
```

Used Versions:
```
Icinga Web 2 Version    2.11.2
PHP Version 7.4.30

Loaded Libraries
icinga/icinga-php-library   0.10.0
icinga/icinga-php-thirdparty    0.11.0

Loaded Modules
azure       0.6.3 
businessprocess     2.4.0 
cube        1.2.2 
director        1.9.1 
grafana     master
idoreports      0.10.0
incubator       0.19.0
map     1.1.0 
monitoring      2.11.2
pdfexport       0.10.2
reporting       0.10.0
```

The Webinterface works fine, but since the font does not load, all icons using the font are not visible.

**Comment by nilmerg** [comment]
Hi,

the UI does not return a 404 without a message. (Just checked) I suspect a webserver configuration issue. If you can't find it yourself, please head over to the [forums](https://community.icinga.com) and ask for help.

If you then still think this is a bug, please create an issue [here](https://github.com/Icinga/icingaweb2/issues) and include steps to reproduce it. The steps shown here only describe a common installation, which can't be the problem. Otherwise we'd have more reports by now.

Best,
Johannes

**Comment by neubi4** [comment]
The UI throws 404 Errors on some pathes without messages, see here: https://github.com/Icinga/icingaweb2/blob/master/library/Icinga/Web/Controller/StaticController.php#L56

Our Problem was that an Apache Reverse Proxy configuration which is in front of our Icingaweb2 added an additional slash (/) at the beginning of every URL, so the Webserver sees `//lib/icinga/icinga-php-library/font/awesome/fa-solid-900.woff2` as the URL.

This works wihtout any problems for everything but this font.

We fixed this at the reverse proxy, so this is working now.
