### ISSUE TITLE
Where can I find icinga-php-library v0.11.0?

### ISSUE THREAD

**Issue by zusa777** [Icinga/icinga-php-library#20]
Hello Icinga Community,

I want to add the certificate monitoring (x509) module to my Icinga 2 installation.
The official Icinga website says that Icinga PHP Library (>= 0.11.0) is required. 
On my Icinga 2 installation I have the ipl v0.10.1 installed. But where can I find the ipl v0.11.0 or above?
On github it says that ipl v.0.10.1 is the latest version.

For me that makes no sense.

Can anyone help me out?
Thanks a lot and have a nice day.

Best regards.

**Comment by yhabteab** [comment]
Hallo @zusa777,

The master branch of the `X509` module is requiring an IPL version, which is not yet released, but will soon be. See https://github.com/Icinga/icingaweb2-module-x509/issues/139#issuecomment-1324826550 to workaround this issue temporarily. Have a nice weekend!

**Comment by zusa777** [comment]
Hello @yhabteab 

Thanks for your fast reply. Do you more or less know when ipl v0.11.0 is out? 

Have also a nice weekend!

**Comment by nilmerg** [comment]
It will be out this week.
