### ISSUE TITLE
Not able to install version 0.10.1

### ISSUE THREAD

**Issue by christoph-pieper** [Icinga/icinga-php-library#21]
When I install icinga-php-library over
```
INSTALL_PATH="/usr/share/icinga-php/ipl"
INSTALL_VERSION="stable/0.10.1"
git clone https://github.com/Icinga/icinga-php-library.git "$INSTALL_PATH" --branch "$INSTALL_VERSION"
```
IcingaWeb2 tells me, that I have unmet dependencies and (I wanted to use [grafana](https://github.com/Mikesch-mp/icingaweb2-module-grafana/blob/master/doc/02-installation.md#requirements)).
![image](https://user-images.githubusercontent.com/29834530/225217457-2ec35571-7c4b-4146-a283-501c0a5ec6da.png)

**Comment by nilmerg** [comment]
Hi, please ask your question in the [forum](https://community.icinga.com/). And make sure to include the output of the commands there and your operating system you're using. Thank you.
