### ISSUE TITLE
Hostgroups destroyed view

### ISSUE THREAD

**Issue by TheCry** [Icinga/icinga-php-library#29]
With the update 0.14.1-1 the display in the ICINGA Webui host group is no longer correct. Here is the screenshot before the update and after the update:
Before update
![icinga-web-hostgroup-ok-view](https://github.com/user-attachments/assets/13c9c74b-08d2-4e19-81af-e3eede906064)

After update
![icinga-web-hostgroup-destroyed-view](https://github.com/user-attachments/assets/16f7e691-c9f1-4edf-9230-3abc40b72dbd)

Now i installed the previous version (0.14.0-1) and the view is fine again.

Regards
Sascha

**Comment by lippserd** [comment]
We just released Icinga DB Web 1.1.3. Installing this version in combination with IPL 0.14.1 should resolve the issue.

**Comment by TheCry** [comment]
Thx.. I'd reveived the update Icinga DB Web 1.1.3 and everythin is fine now.
