### ISSUE TITLE
[install] No valid tag/branch for installations

### ISSUE THREAD

**Issue by Yoda-BZH** [Icinga/icinga-php-library#3]
The readme asks to use a valid branch/tag name for stable installation, but none is available.

Please provide a tag and/or branch to use.

Thank you

**Comment by nilmerg** [comment]
There's https://github.com/Icinga/icinga-php-library/tree/nightly/0.6.0-dev. Rebuilt a moment ago just for you. :smiley:

**Comment by Yoda-BZH** [comment]
I'm not that fond of using a nightly branch in production :D

**Comment by nilmerg** [comment]
Then you should keep using the module.

**Comment by nilmerg** [comment]
Icinga Web 2 Version 2.9.0 is now released and this library also has a stable release now, closing.
