### ISSUE TITLE
Missing module.info

### ISSUE THREAD

**Issue by sol1-matt** [Icinga/icinga-php-library#6]
This is a minor issue but this module is missing module.info

I'm not sure if this omission is on purpose or not, doesn't seem to harm anything if I add the following after installation

```
Name: ipl
Version: 0.6.1
Description: The Icinga PHP library
 This repository ships libraries useful for Icinga Web 2 modules. Please download
 the latest release and install it like any other module.
```

**Comment by nilmerg** [comment]
This isn't a module. It's a library.
